### ISSUE TITLE
DxDataGridDateEditColumn errors on DevExpress.Blazor v20.1.4 or greater

### ISSUE THREAD

**Issue by DeuceL** [DevExpress-Examples/blazor-implement-theme-switcher#1]
As of version 20.1.4, data grid format-related properties of the Spin Edit and Date Edit columns have been renamed.
Line 12 of Index.Razor should be changed 
from: `<DxDataGridDateEditColumn Field="@nameof(WeatherForecast.Date)" DisplayFormatString="D" EditFormatString="d"></DxDataGridDateEditColumn>` 
to: `<DxDataGridDateEditColumn Field="@nameof(WeatherForecast.Date)" DisplayFormat="D" EditorFormat="d"></DxDataGridDateEditColumn>`

https://supportcenter.devexpress.com/ticket/details/t874276/data-grid-format-related-properties-of-the-spin-edit-and-date-edit-columns-have-been

**Comment by zabelin-vladimir** [comment]
Hello,

We recently updated this example and implemented all the necessary changes.
